[package]
name = "bigint-benchmark"
version = "0.2.2"
authors = ["Tomek Czajka <tczajka@gmail.com>"]
edition = "2018"
description = "Benchmarks for big integer implementations"
keywords = ["bigint", "bignum", "mathematics", "benchmark"]
categories = ["mathematics"]
license = "MIT"
repository = "https://github.com/tczajka/bigint-benchmark-rs"
homepage = "https://github.com/tczajka/bigint-benchmark-rs"
readme = "README.md"

[dependencies]
clap = "2.33.3"
ibig = "0.3.4"
num-bigint = "0.4.3"
ramp = "0.7.0"
rug = "1.16.0"
rust-gmp = "0.5.0"
malachite-base = "0.2.2"
malachite-nz = "0.2.2"
